config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
    resources :microposts, :only => [:index]
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'

  match '/contact', :to => "pages#contact"

  match '/about', :to => "pages#about"

  match '/help', :to => "pages#help"

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"

  match '/forgot', :to  => 'users#forgot'
  match '/reset', :to => 'users#reset'
  match '/activate', :to => 'users#activate_user'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
    from being saved:</h2>
  
<p>There were problems with the following fields:</p>
<u1>
  <% object.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </u1>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
<ul class="microposts" summary="User microposts">


<%= render :partial => 'shared/feed_item', :collection => @feed_items %>

</ul>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li class="micropost">
 
  <div class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </div>

 <%= render :partial => 'microposts/delete', :locals => { :post => feed_item } %>

 <%= render :partial => 'microposts/content', :locals => { :post =>  feed_item } %>

 <%= render :partial => 'shared/feed_item', :collection => feed_item.replies %>

</li>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>

<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.hidden_field :parent_id, { :value => params[:parent_id] } %>
  <%= f.text_area :content %>
</div>
<div class="actions">
  <%= f.submit "Submit" %>
</div>

<div class="char_left">
140 characters left.
</div>
<% end %>

<!-- Javascript to update the characters left in micropost content
May have to be refactored later. Seems not correct to have Javascript here. 
I think it should be in application.js -->
<%= javascript_tag do %>

$(document).ready(function(){

  $("#micropost_content").bind('keypress keydown keyup',function(){
    
    var count = 140 - $(this).val().length;
    if (count > 1) {
      $(".char_left").text(count.toString() + " characters left."); 
    }
    else {
      $(".char_left").text(count.toString() + " character left."); 
    }
   });
});


<% end %>

app/views/shared/_stats.html.erb
<% @user ||=current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stats">
            <%= @user.following.size %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stats">
            <%= pluralize(@user.followers.size, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %> ">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>

app/views/shared/_user_sidebar.html.erb
      <strong>Name</strong> <%= @user.name %><br>
      <strong>URL</strong> <%= link_to user_path(@user), @user %>
      <div class="rss"><%= link_to image_tag("feedicons-standard/feed-icon-14x14.png"), url_for(:controller => :users, :action => :show, :format => 'rss') %></div>
      <br>
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>